version: "3.3"
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic_conf.yml:/dynamic_conf.yml
  web:
    image: nginx:latest
    labels:
      - traefik.http.routers.web.rule=Host(`web.docker.localhost`)
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
      - ./web/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
  readme:
    image: nginx:latest
    labels:
      - traefik.http.routers.readme.rule=Host(`readme.docker.localhost`)
    volumes:
      - ./web/readme.html:/usr/share/nginx/html/index.html:ro
      - ./web/favicon.ico:/usr/share/nginx/html/favicon.ico:ro